/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrolement;

import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ismae
 */
public class Formulaire extends javax.swing.JFrame {

    private JComboBox<String> commune;
    private String CNII;

    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    public Formulaire(String CNI){
        this();
        this.CNII = CNI;
        this.CNI.setText(CNI);
        disabled();
        aleatoire();
        
    }
    
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public boolean isRegistered(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/"
                    + "gestioninscriptioncitoyen", "root", "");
            String requete = "SELECT CNI from formulairee WHERE CNI = ?";
            PreparedStatement ps = con.prepareStatement(requete);
            ps.setString(1, CNII);
            ResultSet rs = ps.executeQuery();
            return rs.next();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return true;
        
    }
    
    public void disabled(){
        if(isRegistered()){
            JOptionPane.showMessageDialog(this, 
                    "VOUS ETES DEJA ENREGISTRES", "Attention", JOptionPane.WARNING_MESSAGE);
            nom.setEnabled(false);
            prenom.setEnabled(false);
            datenaissance.setEnabled(false);
            CNI.setEnabled(false);
            antennecommunal.setEnabled(false);
            centrevote.setEnabled(false);
            dateinscription.setEnabled(false);
            soumettre.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datenaissance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        centrevote = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        numeroinscription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateinscription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        soumettre = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CNI = new javax.swing.JTextField();
        antennecommunal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Nom : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 142, -1));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 267, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Date de naisssance :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 152, -1));

        datenaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datenaissanceActionPerformed(evt);
            }
        });
        getContentPane().add(datenaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 267, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Antenne communal :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 152, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Centre de vote :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, 133, -1));

        centrevote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centrevoteActionPerformed(evt);
            }
        });
        getContentPane().add(centrevote, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 730, 270, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Numéro d'incription :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, 160, -1));

        numeroinscription.setEditable(false);
        numeroinscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroinscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(numeroinscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 800, 267, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Date d'inscriptiom :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 860, -1, -1));

        dateinscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateinscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(dateinscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 860, 267, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel9.setText("REPUBLIQUE DU CAMEROUN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel10.setText("REPUBLIQUE OF CAMEROON");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jLabel11.setText("ELECTIONS CAMEROON");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setText("RECEPISSE D'INSCRIPTION- REGISTRAITION RECEIP");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        soumettre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        soumettre.setText("Soumettre");
        soumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soumettreActionPerformed(evt);
            }
        });
        getContentPane().add(soumettre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 950, 240, 70));

        jLabel14.setText("ELECTION-CAMEROUN");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("PAIX-TRAVAIL-PATRIE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("PEACE-WORK-FATHERLAND");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, 20));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Prenom :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 267, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrolement/symbol-cameroon-national-emblem.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 200, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Numero de la carte d'identite :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        CNI.setEditable(false);
        CNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNIActionPerformed(evt);
            }
        });
        getContentPane().add(CNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 270, -1));

        antennecommunal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Douala 1", "Douala 2", "Douala  3", "Douala 4" }));
        antennecommunal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antennecommunalActionPerformed(evt);
            }
        });
        getContentPane().add(antennecommunal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 270, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel8.setText("Name(s)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel13.setText("Surnaes(s)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel19.setText("Date of Birth");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel20.setText("Identity card number");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel21.setText("Council Branch");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel22.setText("Polling Centre");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 760, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel23.setText("Regiatration No");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel24.setText("Registration Date");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel25.setText("format de date: XX-MM-YYYY");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel26.setText("format de date: XX-MM-YYYY");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 880, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void datenaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datenaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datenaissanceActionPerformed

    private void dateinscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateinscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateinscriptionActionPerformed

    private void centrevoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centrevoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centrevoteActionPerformed

    private void soumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soumettreActionPerformed
       
        
        String v1 = nom.getText();
        String v2 = prenom.getText();
        String v3 = datenaissance.getText();
        String v4 = antennecommunal.getItemAt(WIDTH);
        String v5 = centrevote.getItemAt(WIDTH);
        String v6 = numeroinscription.getText();
        String v7 = dateinscription.getText();
        String v8 = CNI.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/"
                    + "gestioninscriptioncitoyen", "root", "");
            String requete = "INSERT INTO formulairee(nom,prenom,datenaissance,"
                    + "antennecommunal,centre_vote,numeroinscription,dateinscription,"
                    + "CNI) values (?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(requete);
            pst.setString(1, v1);
            pst.setString(2, v2);
            pst.setString(3, v3);
            pst.setString(4, v4);
            pst.setString(5, v5);
            pst.setString(6, v6);
            pst.setString(7, v7);
            pst.setString(8, v8);

            pst.executeUpdate();
            String[] v = {v1, v2, v3, v4, v5, v6, v7, v8};
            JOptionPane.showMessageDialog(this, "FELICITATION, VOUS ETES INSCRITS SUR LES LISTES ELECTORALES");
            new Recepisse(v).setVisible(true);
            this.dispose();

// Nous allons recuperer les valeurs des champs
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_soumettreActionPerformed

    public void aleatoire() {
        
        Random rc = new Random();
        String a = "ELECT"+rc.nextInt(999999999);
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306"
                    + "/gestioninscriptioncitoyen", "root", "");
            PreparedStatement ps = con.prepareStatement("SELECT numeroinscription "
                    + "FROM formulairee");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                do{
                    a = "ELECT"+rc.nextInt(999999999);
                }while(rs.getString("numeroinscription").equalsIgnoreCase(a));     
            }
        } catch (SQLException ex) {
            Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        numeroinscription.setText(a);
    }

    private void numeroinscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroinscriptionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_numeroinscriptionActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void antennecommunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antennecommunalActionPerformed
        // TODO add your handling code here:
        
        
        /* String[]a1 = {"Lycee Joss", "Lycee d'Akwa", "Lycee bilingue de Deido",
        "Lycee Technique d'Akwa"};*/
        
        try {
            if (antennecommunal.getSelectedItem().equals("Douala 1")) {
                centrevote.removeAllItems();
                
                centrevote.addItem("Lycee Joss");
                centrevote.addItem("Lycee d'Akwa");
                centrevote.addItem("Lycee bilingue de Deido");
                centrevote.addItem("Lycee Technique d'Akwa");
                centrevote.setSelectedItem(null);
            } else if (antennecommunal.getSelectedItem().equals("Douala 2")) {
                centrevote.removeAllItems();
                centrevote.addItem("Lycee bilingue de new-Bell");
                centrevote.addItem("College evangelique de new-Bell");
                centrevote.addItem("E.CATH.ST.RAYMOND");
                centrevote.setSelectedItem(null);
            } else if (antennecommunal.getSelectedItem().equals("Douala 3")) {
                centrevote.removeAllItems();
                centrevote.addItem("Lycee bilingue de Nyalla ");
                centrevote.addItem("Lycee d'Oyack");
                centrevote.addItem("Lycee de Ndog Hem");
                centrevote.setSelectedItem(null);
            } else if (antennecommunal.getSelectedItem().equals("Douala 4")) {
                centrevote.removeAllItems();
                centrevote.addItem("Lycee bilingue de Bonaberi ");
                centrevote.addItem("College bilingue de Mambanda");
                centrevote.addItem("Lycee de Sodiko");
                centrevote.setSelectedItem(null);
            } else if (antennecommunal.getSelectedItem().equals("Douala 5")) {
                centrevote.removeAllItems();
                centrevote.addItem("Lycee bilingue de Makepe");
                centrevote.addItem("Lycee bilingue de logpom");
                centrevote.addItem("Lycee de la cite des palmiers");
                centrevote.setSelectedItem(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_antennecommunalActionPerformed

    private void CNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNIActionPerformed
        // TODO add your handling code here:
        String v8 = CNI.getText();
        try {

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestioninscriptioncitoyen", "root", "");
            String sql = "SELECT * FROM citoyen WHERE CNI = ? ";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(8, v8);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
            } else {
                JOptionPane.showMessageDialog(this, "Ce numero existe deja.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNI;
    private javax.swing.JComboBox<String> antennecommunal;
    private javax.swing.JComboBox<String> centrevote;
    private javax.swing.JTextField dateinscription;
    private javax.swing.JTextField datenaissance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numeroinscription;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton soumettre;
    // End of variables declaration//GEN-END:variables

}
